FROM oven/bun:1 AS base
WORKDIR /app

COPY . .

RUN bun install
RUN cd apps/web && bun install && cd ../..

RUN bun install

RUN cd packages/db && bun install && bunx prisma generate && cd ../..

RUN cd apps/web && bun run build 

ENV NODE_ENV=production

EXPOSE 3000

CMD ["bun", "start:web"]